/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Benh;
import Service.BenhService;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class BenhUI extends javax.swing.JFrame {

    /**
     * Creates new form BenhUI
     */
    public BenhUI() {
        initComponents();
        setIcon();
        
        setTable();
        hienThiToanBoBenh();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themBenh = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenBenh = new javax.swing.JTextField();
        btbLuuBenh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        suaBenh = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenBenhSua = new javax.swing.JTextField();
        txtMaBenhSua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCapNhatBenh = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBenh = new javax.swing.JTable();
        btnThemBenh = new javax.swing.JButton();
        btnSuaBenh = new javax.swing.JButton();
        btnXoaBenh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        themBenh.setTitle("Thêm bệnh");
        themBenh.setIconImage(null);
        themBenh.setSize(new java.awt.Dimension(380, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tên bệnh:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenBenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btbLuuBenh.setBackground(new java.awt.Color(0, 153, 51));
        btbLuuBenh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuuBenh.setForeground(new java.awt.Color(255, 255, 255));
        btbLuuBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuuBenh.setText("Lưu");
        btbLuuBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuBenhActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btbLuuBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnThoat))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuuBenh)
                    .addComponent(btnThoat))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout themBenhLayout = new javax.swing.GroupLayout(themBenh.getContentPane());
        themBenh.getContentPane().setLayout(themBenhLayout);
        themBenhLayout.setHorizontalGroup(
            themBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        themBenhLayout.setVerticalGroup(
            themBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        suaBenh.setTitle("Sửa bệnh");
        suaBenh.setSize(new java.awt.Dimension(380, 285));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tên bênh:");

        jLabel4.setText("Mã bênh:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(txtTenBenhSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtMaBenhSua, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaBenhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenBenhSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        btnCapNhatBenh.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhatBenh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhatBenh.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhatBenh.setText("Cập nhật");
        btnCapNhatBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatBenhActionPerformed(evt);
            }
        });

        btnThoat1.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat1.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCapNhatBenh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatBenh)
                    .addComponent(btnThoat1))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout suaBenhLayout = new javax.swing.GroupLayout(suaBenh.getContentPane());
        suaBenh.getContentPane().setLayout(suaBenhLayout);
        suaBenhLayout.setHorizontalGroup(
            suaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        suaBenhLayout.setVerticalGroup(
            suaBenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản lí bệnh");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbBenh = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbBenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbBenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBenhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbBenh);

        btnThemBenh.setBackground(new java.awt.Color(0, 153, 51));
        btnThemBenh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemBenh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemBenh.setText("Thêm");
        btnThemBenh.setToolTipText("");
        btnThemBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBenhActionPerformed(evt);
            }
        });

        btnSuaBenh.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaBenh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaBenh.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaBenh.setText("Sửa");
        btnSuaBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaBenhActionPerformed(evt);
            }
        });

        btnXoaBenh.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaBenh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaBenh.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaBenh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaBenh.setText("Xóa");
        btnXoaBenh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaBenhActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách bệnh");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnThemBenh)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaBenh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemBenh)
                    .addComponent(btnSuaBenh)
                    .addComponent(btnXoaBenh))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> header = new Vector<>();
    Vector<Object> data  = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Mã bệnh");
        header.add("Tên bệnh");
     
        model = (DefaultTableModel) tbBenh.getModel();    
        model.setDataVector(data, header);
    }
    
    ArrayList<Benh> dsBenh = null;
    public void hienThiToanBoBenh(){
        BenhService benhService = new BenhService();
        dsBenh = benhService.layToanBoBenh();
        
        model.setRowCount(0);
        for (Benh benh : dsBenh) {
            Vector row = new Vector();
            row.add(benh.getMaBenh());
            row.add(benh.getTenBenh());
            
            data.add(row);
        }
        
    }
    String maBenh;
    private void tbBenhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBenhMouseClicked
        int row = tbBenh.getSelectedRow();
        maBenh = tbBenh.getValueAt(row, 0).toString();
        String tenBenh = tbBenh.getValueAt(row, 1).toString();
        
        txtMaBenhSua.setText(maBenh);
        txtTenBenhSua.setText(tenBenh);
               
    }//GEN-LAST:event_tbBenhMouseClicked

    private void btnThemBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBenhActionPerformed
        
       themBenh.setVisible(true);
       themBenh.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_btnThemBenhActionPerformed

    private void btnSuaBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaBenhActionPerformed
        if (maBenh == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bệnh");
            return;
        }
        suaBenh.setVisible(true);
        suaBenh.setLocationRelativeTo(null);
        txtMaBenhSua.disable();
        
    }//GEN-LAST:event_btnSuaBenhActionPerformed

    private void btnXoaBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaBenhActionPerformed
        // TODO add your handling code here:
        
        if (maBenh == null) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn bệnh để xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if ( confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        Benh benh = new Benh();
        benh.setMaBenh(Integer.parseInt(maBenh));
        BenhService benhService = new BenhService();
        int result = benhService.xoaBenh(benh);
        if (result >0) {
            hienThiToanBoBenh();
            JOptionPane.showMessageDialog(null, "Đã xóa");
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaBenhActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DanhMucThuocVaBenhUI danhMucThuocVaBenhUI = new DanhMucThuocVaBenhUI();
       danhMucThuocVaBenhUI.setVisible(true);
       danhMucThuocVaBenhUI.setLocationRelativeTo(null);
       this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuBenhActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        
        Benh benh = new Benh();
        //check ten benh
        if (trangChuUI.checkDoDai(txtTenBenh.getText(), 1, 50)) {
            benh.setTenBenh(txtTenBenh.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Tên bệnh không hợp lệ");
            txtTenBenh.requestFocus();
            return;
        }
        
        BenhService benhService = new BenhService();
        int result = benhService.themBenh(benh);
        if (result > 0) {
            hienThiToanBoBenh();
            JOptionPane.showMessageDialog(null, "Đã thêm");
        }else{
            JOptionPane.showMessageDialog(null, "Tên bệnh đã tồn tại");
        }

    }//GEN-LAST:event_btbLuuBenhActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        themBenh.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCapNhatBenhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatBenhActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        Benh benh = new Benh();
        benh.setMaBenh(Integer.parseInt(maBenh));
        if (trangChuUI.checkDoDai(txtTenBenhSua.getText(), 1, 50)) {
            benh.setTenBenh(txtTenBenhSua.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Tên bệnh không hợp lệ");
            txtMaBenhSua.requestFocus();
            return;
        }
        
        BenhService benhService = new BenhService();
        int result = benhService.suaBenh(benh);
        
        if (result > 0) {
            hienThiToanBoBenh();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Tên bệnh đã tồn tại. Vui lòng kiểm tra lại");
        }
               

    }//GEN-LAST:event_btnCapNhatBenhActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        // TODO add your handling code here:
       suaBenh.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BenhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BenhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BenhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BenhUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BenhUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbLuuBenh;
    private javax.swing.JButton btnCapNhatBenh;
    private javax.swing.JButton btnSuaBenh;
    private javax.swing.JButton btnThemBenh;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoaBenh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog suaBenh;
    private javax.swing.JTable tbBenh;
    private javax.swing.JDialog themBenh;
    private javax.swing.JTextField txtMaBenhSua;
    private javax.swing.JTextField txtTenBenh;
    private javax.swing.JTextField txtTenBenhSua;
    // End of variables declaration//GEN-END:variables

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
    }
}
