/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.DoiTuongBenhNhan;
import Service.DoiTuongBenhNhanService;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class DoiTuongBenhNhanUI extends javax.swing.JFrame {

    /**
     * Creates new form DoiTuongBenhNhanUI
     */
    public DoiTuongBenhNhanUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
        hienThiToanBoDoiTuongBenhNhan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemDoiTuongBenhNhan = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDoiTuongBenhNhan = new javax.swing.JTextField();
        btbLuuDoiTuongBenhNhan = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        SuaDoiTuongBenhNhan = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDoiTuongBenhNhanSua = new javax.swing.JTextField();
        txtMaDoiTuongBenhNhanSua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoiTuongBenhNhan = new javax.swing.JTable();
        btnThemDoiTuongBenhNhan = new javax.swing.JButton();
        btnSuaDoiTuongBenhNhan = new javax.swing.JButton();
        btnXoaDoiTuongBenhNhan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        ThemDoiTuongBenhNhan.setSize(new java.awt.Dimension(380, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tên đối tượng bệnh nhân:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btbLuuDoiTuongBenhNhan.setBackground(new java.awt.Color(0, 153, 51));
        btbLuuDoiTuongBenhNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuuDoiTuongBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btbLuuDoiTuongBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuuDoiTuongBenhNhan.setText("Lưu");
        btbLuuDoiTuongBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuDoiTuongBenhNhanActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btbLuuDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnThoat))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuuDoiTuongBenhNhan)
                    .addComponent(btnThoat))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemDoiTuongBenhNhanLayout = new javax.swing.GroupLayout(ThemDoiTuongBenhNhan.getContentPane());
        ThemDoiTuongBenhNhan.getContentPane().setLayout(ThemDoiTuongBenhNhanLayout);
        ThemDoiTuongBenhNhanLayout.setHorizontalGroup(
            ThemDoiTuongBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ThemDoiTuongBenhNhanLayout.setVerticalGroup(
            ThemDoiTuongBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaDoiTuongBenhNhan.setSize(new java.awt.Dimension(380, 285));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tên đối tượng bệnh nhân:");

        jLabel4.setText("Mã đối tượng bênh nhân:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(txtTenDoiTuongBenhNhanSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtMaDoiTuongBenhNhanSua, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaDoiTuongBenhNhanSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDoiTuongBenhNhanSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat1.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat1.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat1))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaDoiTuongBenhNhanLayout = new javax.swing.GroupLayout(SuaDoiTuongBenhNhan.getContentPane());
        SuaDoiTuongBenhNhan.getContentPane().setLayout(SuaDoiTuongBenhNhanLayout);
        SuaDoiTuongBenhNhanLayout.setHorizontalGroup(
            SuaDoiTuongBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuaDoiTuongBenhNhanLayout.setVerticalGroup(
            SuaDoiTuongBenhNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbDoiTuongBenhNhan = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbDoiTuongBenhNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDoiTuongBenhNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDoiTuongBenhNhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDoiTuongBenhNhan);

        btnThemDoiTuongBenhNhan.setBackground(new java.awt.Color(0, 153, 51));
        btnThemDoiTuongBenhNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemDoiTuongBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDoiTuongBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemDoiTuongBenhNhan.setText("Thêm");
        btnThemDoiTuongBenhNhan.setToolTipText("");
        btnThemDoiTuongBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDoiTuongBenhNhanActionPerformed(evt);
            }
        });

        btnSuaDoiTuongBenhNhan.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaDoiTuongBenhNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaDoiTuongBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaDoiTuongBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaDoiTuongBenhNhan.setText("Sửa");
        btnSuaDoiTuongBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDoiTuongBenhNhanActionPerformed(evt);
            }
        });

        btnXoaDoiTuongBenhNhan.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaDoiTuongBenhNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaDoiTuongBenhNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDoiTuongBenhNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaDoiTuongBenhNhan.setText("Xóa");
        btnXoaDoiTuongBenhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDoiTuongBenhNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách đối tượng bệnh nhân");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnThemDoiTuongBenhNhan)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel1)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDoiTuongBenhNhan)
                    .addComponent(btnSuaDoiTuongBenhNhan)
                    .addComponent(btnXoaDoiTuongBenhNhan))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> header = new Vector<>();
    Vector<Object> data  = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Mã đối tượng bệnh nhân");
        header.add("Tên đối tượng bệnh nhân");
     
        model = (DefaultTableModel) tbDoiTuongBenhNhan.getModel();    
        model.setDataVector(data, header);
    }
    
    ArrayList<DoiTuongBenhNhan> dsDoiTuongBenhNhan=null;
    public void hienThiToanBoDoiTuongBenhNhan(){
        DoiTuongBenhNhanService doiTuongBenhNhanService = new DoiTuongBenhNhanService();
        dsDoiTuongBenhNhan = doiTuongBenhNhanService.layToanBoDoiTuongBenhNhan();
        
        model.setRowCount(0);
        for (DoiTuongBenhNhan doiTuongBenhNhan : dsDoiTuongBenhNhan) {
            Vector row = new Vector();
            row.add(doiTuongBenhNhan.getMaDoiTuongBenhNhan());
            row.add(doiTuongBenhNhan.getTenDoiTuongBenhNhan());
            
            data.add(row);
        }
    }
    String maDoiTuongBenhNhan;
    private void tbDoiTuongBenhNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDoiTuongBenhNhanMouseClicked
        // TODO add your handling code here:
        int row = tbDoiTuongBenhNhan.getSelectedRow();
        maDoiTuongBenhNhan = tbDoiTuongBenhNhan.getValueAt(row, 0).toString();
        String tenDoiTuonBenhNhan = tbDoiTuongBenhNhan.getValueAt(row, 1).toString();

        txtMaDoiTuongBenhNhanSua.setText(maDoiTuongBenhNhan);
        txtTenDoiTuongBenhNhanSua.setText(tenDoiTuonBenhNhan);
    }//GEN-LAST:event_tbDoiTuongBenhNhanMouseClicked

    private void btnThemDoiTuongBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDoiTuongBenhNhanActionPerformed
        // TODO add your handling code here:
        ThemDoiTuongBenhNhan.setVisible(true);
        ThemDoiTuongBenhNhan.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnThemDoiTuongBenhNhanActionPerformed

    private void btnSuaDoiTuongBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDoiTuongBenhNhanActionPerformed
        // TODO add your handling code here:
        if (maDoiTuongBenhNhan == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn đối tượng bện nhân");
            return;
        }
        SuaDoiTuongBenhNhan.setVisible(true);
        SuaDoiTuongBenhNhan.setLocationRelativeTo(null);
        txtMaDoiTuongBenhNhanSua.disable();

    }//GEN-LAST:event_btnSuaDoiTuongBenhNhanActionPerformed

    private void btnXoaDoiTuongBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDoiTuongBenhNhanActionPerformed
        // TODO add your handling code here:
        if (maDoiTuongBenhNhan == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn đối tương bệnh nhân cần xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        DoiTuongBenhNhan doiTuongBenhNhan = new DoiTuongBenhNhan();
        doiTuongBenhNhan.setMaDoiTuongBenhNhan(Integer.parseInt(maDoiTuongBenhNhan));
        DoiTuongBenhNhanService doiTuongBenhNhanService = new DoiTuongBenhNhanService();
        int result = doiTuongBenhNhanService.xoaDoiTuongBenhNhan(doiTuongBenhNhan);
        if (result > 0) {
            hienThiToanBoDoiTuongBenhNhan();
            JOptionPane.showMessageDialog(null, "Đã xóa");
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaDoiTuongBenhNhanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoiTuongBenhNhanVaSuDungThuocUI doiTuongBenhNhanVaSuDungThuocUI = new DoiTuongBenhNhanVaSuDungThuocUI();
        doiTuongBenhNhanVaSuDungThuocUI.setVisible(true);
        doiTuongBenhNhanVaSuDungThuocUI.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuDoiTuongBenhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuDoiTuongBenhNhanActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        DoiTuongBenhNhan doiTuongBenhNhan = new DoiTuongBenhNhan();
        
        if (trangChuUI.checkDoDai(txtTenDoiTuongBenhNhan.getText(), 1, 50)) {
            doiTuongBenhNhan.setTenDoiTuongBenhNhan(txtTenDoiTuongBenhNhan.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Tên đối tượng bệnh nhân không hợp lệ");
            return;
        }
        
        DoiTuongBenhNhanService doiTuongBenhNhanService = new DoiTuongBenhNhanService();
        int result = doiTuongBenhNhanService.themDoiTuongBenhNhan(doiTuongBenhNhan);
        
        if (result > 0) {
            hienThiToanBoDoiTuongBenhNhan();
            JOptionPane.showMessageDialog(null, "Đã thêm");
        }else{
            JOptionPane.showMessageDialog(null, "Tên đối tượng bênh nhân đã tồn tại. Vui lòng kiểm tra lại");
        }
        
    }//GEN-LAST:event_btbLuuDoiTuongBenhNhanActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        ThemDoiTuongBenhNhan.dispose();

    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        DoiTuongBenhNhan doiTuongBenhNhan = new DoiTuongBenhNhan();
        doiTuongBenhNhan.setMaDoiTuongBenhNhan(Integer.parseInt(maDoiTuongBenhNhan));

        if (trangChuUI.checkDoDai(txtTenDoiTuongBenhNhanSua.getText(), 1, 50)) {

            doiTuongBenhNhan.setTenDoiTuongBenhNhan(txtTenDoiTuongBenhNhanSua.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Tên đối tượng bệnh nhân không hợp lệ");
            return;
        }

        DoiTuongBenhNhanService doiTuongBenhNhanService = new DoiTuongBenhNhanService();
        int result = doiTuongBenhNhanService.suaDoiTuongBenhNhan(doiTuongBenhNhan);
        if (result > 0) {
            hienThiToanBoDoiTuongBenhNhan();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Đối tượng bệnh nhân đã tồn tại. Vui lòng kiêm tra lại");
            return;

        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        // TODO add your handling code here:
        SuaDoiTuongBenhNhan.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiTuongBenhNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiTuongBenhNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiTuongBenhNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiTuongBenhNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiTuongBenhNhanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaDoiTuongBenhNhan;
    private javax.swing.JDialog ThemDoiTuongBenhNhan;
    private javax.swing.JButton btbLuuDoiTuongBenhNhan;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSuaDoiTuongBenhNhan;
    private javax.swing.JButton btnThemDoiTuongBenhNhan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoaDoiTuongBenhNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDoiTuongBenhNhan;
    private javax.swing.JTextField txtMaDoiTuongBenhNhanSua;
    private javax.swing.JTextField txtTenDoiTuongBenhNhan;
    private javax.swing.JTextField txtTenDoiTuongBenhNhanSua;
    // End of variables declaration//GEN-END:variables
}
