/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.CoLieuLuongDung;
import Model.DoiTuongBenhNhan;
import Model.DungCho;
import Model.Thuoc;
import Service.CoLieuLuongDungService;
import Service.DoiTuongBenhNhanService;
import Service.DungChoService;
import Service.ThuocService;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class DungChoUI extends javax.swing.JFrame {

    /**
     * Creates new form DungChoUI
     */
    public DungChoUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemDungCho = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbThuoc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDoiTuongBenhNhan = new javax.swing.JComboBox<>();
        btbLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        SuaDungCho = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbThuocSua = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbDoiTuongBenhNhanSua = new javax.swing.JComboBox<>();
        btnCapNhat = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDungCho = new javax.swing.JTable();
        btnThemDungCho = new javax.swing.JButton();
        btnSuaDungCho = new javax.swing.JButton();
        btnXoaDungCho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        ThemDungCho.setSize(new java.awt.Dimension(415, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Thuốc:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Đối tượng bệnh nhân:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(cbThuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDoiTuongBenhNhan, 0, 200, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDoiTuongBenhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btbLuu.setBackground(new java.awt.Color(0, 153, 51));
        btbLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuu.setForeground(new java.awt.Color(255, 255, 255));
        btbLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuu.setText("Lưu");
        btbLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btbLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuu)
                    .addComponent(btnThoat))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemDungChoLayout = new javax.swing.GroupLayout(ThemDungCho.getContentPane());
        ThemDungCho.getContentPane().setLayout(ThemDungChoLayout);
        ThemDungChoLayout.setHorizontalGroup(
            ThemDungChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThemDungChoLayout.setVerticalGroup(
            ThemDungChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaDungCho.setSize(new java.awt.Dimension(415, 310));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Thuốc:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Đối tượng bệnh nhân:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(cbThuocSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDoiTuongBenhNhanSua, 0, 200, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbThuocSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDoiTuongBenhNhanSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat1.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat1.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addGap(81, 81, 81)
                        .addComponent(btnThoat1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat1))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaDungChoLayout = new javax.swing.GroupLayout(SuaDungCho.getContentPane());
        SuaDungCho.getContentPane().setLayout(SuaDungChoLayout);
        SuaDungChoLayout.setHorizontalGroup(
            SuaDungChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuaDungChoLayout.setVerticalGroup(
            SuaDungChoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbDungCho = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbDungCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDungCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDungChoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDungCho);

        btnThemDungCho.setBackground(new java.awt.Color(0, 153, 51));
        btnThemDungCho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemDungCho.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDungCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemDungCho.setText("Thêm");
        btnThemDungCho.setToolTipText("");
        btnThemDungCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDungChoActionPerformed(evt);
            }
        });

        btnSuaDungCho.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaDungCho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaDungCho.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaDungCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaDungCho.setText("Sửa");
        btnSuaDungCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDungChoActionPerformed(evt);
            }
        });

        btnXoaDungCho.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaDungCho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaDungCho.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDungCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaDungCho.setText("Xóa");
        btnXoaDungCho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDungChoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách thuốc dùng cho đối tượng bệnh nhân");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnThemDungCho)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaDungCho, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDungCho, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDungCho)
                    .addComponent(btnSuaDungCho)
                    .addComponent(btnXoaDungCho))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> header = new Vector<>();
    Vector<Object> data  = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Tên thuốc");
        header.add("Đối tượng bệnh nhân");
        
        model = (DefaultTableModel) tbDungCho.getModel();    
        model.setDataVector(data, header);
    }
    
    ArrayList<DungCho> dsDungCho =null;
    public void hienThiToanBoDungCho(){
        DungChoService dungChoService = new DungChoService();
        dsDungCho = dungChoService.layToanBoDungCho();
        
        model.setRowCount(0);
        for (DungCho dungCho : dsDungCho) {
            Vector row = new Vector();
            row.add(dungCho.getMaThuoc() +"_"+dungCho.getTenThuoc());
            row.add(dungCho.getMaDoiTuongBenhNhan()+"-"+dungCho.getTenDoiTuongBenhNhan());
            
            data.add(row);
        }
    }
    
    public void hienThiToanBoThuoc(){
        ArrayList<Thuoc> dsThuoc = null;
        ThuocService thuocService  = new ThuocService();
        dsThuoc = thuocService.layToanBoThongTinThuoc();
        
        for (Thuoc thuoc : dsThuoc) {
            cbThuoc.addItem(thuoc.getMaThuoc()+"_"+thuoc.getTenThuoc());
        }
        
    }
    
    public void hienThiToanBoThuocSua(){
        ArrayList<Thuoc> dsThuoc = null;
        ThuocService thuocService  = new ThuocService();
        dsThuoc = thuocService.layToanBoThongTinThuoc();
        
        for (Thuoc thuoc : dsThuoc) {
            cbThuocSua.addItem(thuoc.getMaThuoc()+"_"+thuoc.getTenThuoc());
        }
        
    }
    
    public void hienThiToanDoiTuongBenhNhan(){
        ArrayList<DoiTuongBenhNhan> dsDoiTuongBenhNhan = null;
        DoiTuongBenhNhanService doiTuongBenhNhanService  = new DoiTuongBenhNhanService();
        dsDoiTuongBenhNhan = doiTuongBenhNhanService.layToanBoDoiTuongBenhNhan();
        
        for (DoiTuongBenhNhan doiTuongBenhNhan : dsDoiTuongBenhNhan) {
            cbDoiTuongBenhNhan.addItem(doiTuongBenhNhan.getMaDoiTuongBenhNhan()+"-"+doiTuongBenhNhan.getTenDoiTuongBenhNhan());
        }
        
    }
    
    public void hienThiToanDoiTuongBenhNhanSua(){
        ArrayList<DoiTuongBenhNhan> dsDoiTuongBenhNhan = null;
        DoiTuongBenhNhanService doiTuongBenhNhanService  = new DoiTuongBenhNhanService();
        dsDoiTuongBenhNhan = doiTuongBenhNhanService.layToanBoDoiTuongBenhNhan();
        
        for (DoiTuongBenhNhan doiTuongBenhNhan : dsDoiTuongBenhNhan) {
            cbDoiTuongBenhNhanSua.addItem(doiTuongBenhNhan.getMaDoiTuongBenhNhan()+"-"+doiTuongBenhNhan.getTenDoiTuongBenhNhan());
        }
        
    }
    
    String maThuoc;
    String maDoiTuongBenhNhan;
    private void tbDungChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDungChoMouseClicked
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();

        cbThuocSua.removeAllItems();
        cbDoiTuongBenhNhanSua.removeAllItems();
        hienThiToanBoThuocSua();
        hienThiToanDoiTuongBenhNhanSua();

        int row = tbDungCho.getSelectedRow();
        String maThuocVaTenThuoc = tbDungCho.getValueAt(row, 0).toString();
        String maVaTenDoiTuongBenhNhan = tbDungCho.getValueAt(row, 1).toString();
        
        //Tach lay ma
        maThuoc = trangChuUI.ngatChuoi(maThuocVaTenThuoc, "_", 0);
        maDoiTuongBenhNhan = trangChuUI.ngatChuoi(maVaTenDoiTuongBenhNhan, "-", 0);
        //add vao form sua
        cbThuocSua.setSelectedItem(maThuocVaTenThuoc);
        cbDoiTuongBenhNhanSua.setSelectedItem(maVaTenDoiTuongBenhNhan);
        
    }//GEN-LAST:event_tbDungChoMouseClicked

    private void btnThemDungChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDungChoActionPerformed
        // TODO add your handling code here:
        ThemDungCho.setVisible(true);
        ThemDungCho.setLocationRelativeTo(null);

        cbThuoc.removeAllItems();
        cbDoiTuongBenhNhan.removeAllItems();
        hienThiToanBoThuoc();
        hienThiToanDoiTuongBenhNhan();
    }//GEN-LAST:event_btnThemDungChoActionPerformed

    private void btnSuaDungChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDungChoActionPerformed
        // TODO add your handling code here:
        if ( maThuoc == null && maDoiTuongBenhNhan == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn thuốc");
            return;
        }
        SuaDungCho.setVisible(true);
        SuaDungCho.setLocationRelativeTo(null);
        cbThuocSua.disable();
    }//GEN-LAST:event_btnSuaDungChoActionPerformed

    private void btnXoaDungChoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDungChoActionPerformed
        // TODO add your handling code here:
        if (maThuoc == null && maDoiTuongBenhNhan == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn thuốc cần xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        DungCho dungCho = new DungCho();
        dungCho.setMaThuoc(maThuoc);
        dungCho.setMaDoiTuongBenhNhan(Integer.parseInt(maDoiTuongBenhNhan));

        DungChoService dungChoService = new DungChoService();
        int result = dungChoService.xoaDungCho(dungCho);
        if (result > 0) {
            hienThiToanBoDungCho();
            JOptionPane.showMessageDialog(null, "Đã xóa");
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaDungChoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoiTuongBenhNhanVaSuDungThuocUI doiTuongBenhNhanVaSuDungThuocUI = new DoiTuongBenhNhanVaSuDungThuocUI();
        doiTuongBenhNhanVaSuDungThuocUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        DungCho dungCho = new DungCho();

        //Ma thuoc
        String maThuoc = trangChuUI.ngatChuoi(cbThuoc.getSelectedItem().toString(), "_", 0);
        dungCho.setMaThuoc(maThuoc);
        //Ma doi tuong benh nhan
        String maDoiTuongBenhNhan = trangChuUI.ngatChuoi(cbDoiTuongBenhNhan.getSelectedItem().toString() , "-", 0);
        dungCho.setMaDoiTuongBenhNhan(Integer.parseInt(maDoiTuongBenhNhan));
        
        DungChoService dungChoService = new DungChoService();
        int result = dungChoService.themDungCho(dungCho);
        if (result > 0) {
            hienThiToanBoDungCho();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(null, "Thuốc dùng cho đối tượng bệnh nhân đã được thêm trước đó. Vui lòng kiêm tra lại");
        }
    }//GEN-LAST:event_btbLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        ThemDungCho.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();

        DungCho dungCho = new DungCho();
        String maDoiTuongBenhNhanSua = trangChuUI.ngatChuoi((String) cbDoiTuongBenhNhanSua.getSelectedItem(), "-", 0);
        dungCho.setMaDoiTuongBenhNhan(Integer.parseInt(maDoiTuongBenhNhanSua));

        dungCho.setMaThuocSua(maThuoc);
        dungCho.setMaDoiTuongBenhNhanSua(Integer.parseInt(maDoiTuongBenhNhan));

        DungChoService dungChoService  = new DungChoService();
        int result = dungChoService.suaDungCho(dungCho);
        if (result > 0) {
            hienThiToanBoDungCho();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Thuốc dùng cho đối tượng bênh nhân đã được cập trước đó. Vui lòng kiểm tra lại");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        // TODO add your handling code here:
        SuaDungCho.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DungChoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DungChoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DungChoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DungChoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DungChoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaDungCho;
    private javax.swing.JDialog ThemDungCho;
    private javax.swing.JButton btbLuu;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSuaDungCho;
    private javax.swing.JButton btnThemDungCho;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoaDungCho;
    private javax.swing.JComboBox<String> cbDoiTuongBenhNhan;
    private javax.swing.JComboBox<String> cbDoiTuongBenhNhanSua;
    private javax.swing.JComboBox<String> cbThuoc;
    private javax.swing.JComboBox<String> cbThuocSua;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbDungCho;
    // End of variables declaration//GEN-END:variables
}
