/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.HoaDonNhap;
import Model.Lo;
import Model.Thuoc;
import Service.HoaDonNhapService;
import Service.LoService;
import Service.NhomThuocService;
import Service.ThuocService;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class LoUI extends javax.swing.JFrame {

    /**
     * Creates new form LoUI
     */
    public LoUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemLo = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        btbLuu = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbSoChungTuNhap = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgaySanXuat = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtHanSuDung = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDonGiaVon = new javax.swing.JTextField();
        cbMaThuoc = new javax.swing.JComboBox<>();
        SuaLo = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        btbCapNhat = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtMaLoSua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbSoChungTuNhapSua = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNgaySanXuatSua = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtHanSuDungSua = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtGiaBanSua = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSoLuongSua = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDonGiaVonSua = new javax.swing.JTextField();
        cbMaThuocSua = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbLo = new javax.swing.JTable();
        btnThemLo = new javax.swing.JButton();
        btnSuaLo = new javax.swing.JButton();
        btnXoaLo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        ThemLo.setSize(new java.awt.Dimension(440, 660));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btbLuu.setBackground(new java.awt.Color(0, 153, 51));
        btbLuu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuu.setForeground(new java.awt.Color(255, 255, 255));
        btbLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuu.setText("Lưu");
        btbLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã lô:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Số chứng từ nhập:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tên thuốc:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ngày sản xuất:");

        txtNgaySanXuat.setDateFormatString("yyyy-MM-d");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hạn sử dụng:");

        txtHanSuDung.setDateFormatString("yyyy-MM-d");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Giá bán:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Số lượng:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Đơn giá vốn:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLo)
                    .addComponent(cbSoChungTuNhap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtHanSuDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaBan)
                    .addComponent(txtDonGiaVon)
                    .addComponent(cbMaThuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSoChungTuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgaySanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDonGiaVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btbLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jButton5))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btbLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemLoLayout = new javax.swing.GroupLayout(ThemLo.getContentPane());
        ThemLo.getContentPane().setLayout(ThemLoLayout);
        ThemLoLayout.setHorizontalGroup(
            ThemLoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ThemLoLayout.setVerticalGroup(
            ThemLoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaLo.setSize(new java.awt.Dimension(440, 660));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        btbCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btbCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btbCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbCapNhat.setText("Cập nhật");
        btbCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCapNhatActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        jButton6.setText("Thoát");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Mã lô:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Số chứng từ nhập:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Tên thuốc:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Ngày sản xuất:");

        txtNgaySanXuatSua.setDateFormatString("yyyy-MM-d");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Hạn sử dụng:");

        txtHanSuDungSua.setDateFormatString("yyyy-MM-d");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Giá bán:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Số lượng:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Đơn giá vốn:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuongSua, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(txtMaLoSua)
                    .addComponent(cbSoChungTuNhapSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgaySanXuatSua, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtHanSuDungSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGiaBanSua)
                    .addComponent(txtDonGiaVonSua)
                    .addComponent(cbMaThuocSua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSoChungTuNhapSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaLoSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMaThuocSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNgaySanXuatSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHanSuDungSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGiaBanSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSoLuongSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDonGiaVonSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btbCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btbCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaLoLayout = new javax.swing.GroupLayout(SuaLo.getContentPane());
        SuaLo.getContentPane().setLayout(SuaLoLayout);
        SuaLoLayout.setHorizontalGroup(
            SuaLoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        SuaLoLayout.setVerticalGroup(
            SuaLoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tbLo = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbLo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbLo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbLo);

        btnThemLo.setBackground(new java.awt.Color(0, 153, 51));
        btnThemLo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemLo.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemLo.setText("Thêm");
        btnThemLo.setToolTipText("");
        btnThemLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoActionPerformed(evt);
            }
        });

        btnSuaLo.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaLo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaLo.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaLo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaLo.setText("Sửa");
        btnSuaLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoActionPerformed(evt);
            }
        });

        btnXoaLo.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaLo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaLo.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaLo.setText("Xóa");
        btnXoaLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách lô thuốc");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemLo)
                .addGap(18, 18, 18)
                .addComponent(btnSuaLo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaLo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemLo)
                    .addComponent(btnSuaLo)
                    .addComponent(btnXoaLo))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> header = new Vector<>();
    Vector<Object> data  = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Số chứng từ nhập");
        header.add("Mã lô");
        header.add("Tên thuốc");
        header.add("Ngày sản xuất");
        header.add("Hạn sử dụng");
        header.add("Giá bán(VND)");
        header.add("Số lượng");
        header.add("Đơn giá vốn(VND)");
        
        model = (DefaultTableModel) tbLo.getModel();    
        model.setDataVector(data, header);
    }
    
    ArrayList<Lo> dsLo = null;
    public void hienThiToanBoLo(){
        LoService loService = new LoService();
        dsLo = loService.layToanBoLo();
        
        //fotmat number 
        NumberFormat currentLocale = NumberFormat.getInstance();
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        
        model.setRowCount(0);
        for (Lo lo : dsLo) {
            Vector row = new Vector();
            row.add(lo.getSoChungTuNhap());
            row.add(lo.getMaLo());
            row.add(lo.getMaThuoc()+"_"+lo.getTenThuoc());
            row.add(lo.getNgaySanXuat());
            row.add(lo.getHanSuDung());
            row.add(vn.format(lo.getGiaBan()));
            row.add(lo.getSoLuong());
            row.add(vn.format(lo.getDonGiaVon()));
            
            data.add(row);
        }
    }
    
    String maLo;
    private void tbLoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoMouseClicked
        // TODO add your handling code here:
        int row = tbLo.getSelectedRow();
        
        String soChungTuNhap = tbLo.getValueAt(row, 0).toString();
        maLo  = (String) tbLo.getValueAt(row, 1);
        String maThuocVaTenThuoc = (String) tbLo.getValueAt(row, 2);
        String ngaySanXuat = (String) tbLo.getValueAt(row, 3);
        String hanSuDung = (String) tbLo.getValueAt(row, 4);
        String giaBan = tbLo.getValueAt(row, 5).toString();
        String soLuong =  tbLo.getValueAt(row, 6).toString();
        String donGiaVon = tbLo.getValueAt(row, 7).toString();
        
        hienThiSoChungTuNhapSua();
        hienThiTenThuocSua();
        cbSoChungTuNhapSua.setSelectedItem(soChungTuNhap);
        txtMaLoSua.setText(maLo);
        cbMaThuocSua.setSelectedItem(maThuocVaTenThuoc);
        
        try {
            Date fmNgaySanXuat = new SimpleDateFormat("yyyy-MM-dd").parse(ngaySanXuat);
            txtNgaySanXuatSua.setDate(fmNgaySanXuat);
            Date fmHanSuDung = new SimpleDateFormat("yyyy-MM-dd").parse(hanSuDung);
            txtHanSuDungSua.setDate(fmHanSuDung);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonNhapUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtGiaBanSua.setText(giaBan.replace(".", ""));
        txtSoLuongSua.setText(soLuong);
        txtDonGiaVonSua.setText(donGiaVon.replace(".", ""));
        
    }//GEN-LAST:event_tbLoMouseClicked

    private void btnThemLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoActionPerformed
        // TODO add your handling code here:
        ThemLo.setVisible(true);
        ThemLo.setLocationRelativeTo(null);
        hienThiSoChungTuNhap();
        hienThiTenThuoc();
        txtNgaySanXuat.getDateEditor().setEnabled(false);
        txtHanSuDung.getDateEditor().setEnabled(false);
    }//GEN-LAST:event_btnThemLoActionPerformed

    private void btnSuaLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoActionPerformed
        // TODO add your handling code here:
        if (maLo == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn lô thuốc");
            return;
        }
        SuaLo.setVisible(true);
        SuaLo.setLocationRelativeTo(null);
        txtMaLoSua.disable();
        txtNgaySanXuatSua.getDateEditor().setEnabled(false);
        txtHanSuDungSua.getDateEditor().setEnabled(false);

    }//GEN-LAST:event_btnSuaLoActionPerformed

    private void btnXoaLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoActionPerformed
        // TODO add your handling code here:
        if (maLo == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn lô thuốc cần xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Lo lo = new Lo();
        lo.setMaLo(maLo);
        LoService loService = new LoService();
        int result = loService.xoaLo(lo);
        if (result > 0) {
            hienThiToanBoLo();
            JOptionPane.showMessageDialog(null, "Đã xóa");
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaLoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NhapThuocUI nhapThuocUI = new NhapThuocUI();
        nhapThuocUI.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuActionPerformed

        TrangChuUI trangChuUI = new TrangChuUI();
        Lo lo = new Lo();
        //ma lo
        if (trangChuUI.checkDoDai(txtMaLo.getText(), 1, 5)) {
            lo.setMaLo(txtMaLo.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Mã lô không hợp lệ");
            txtMaLo.requestFocus();
            return;
        }
        
        //so chung tu nhap
        lo.setSoChungTuNhap(Integer.parseInt(cbSoChungTuNhap.getSelectedItem().toString()));
        
        //Ma thuoc
        lo.setMaThuoc(trangChuUI.ngatChuoi((String) cbMaThuoc.getSelectedItem(), "_", 0));
        
        //ngay san xuat
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (txtNgaySanXuat.getDate() != null) {
            lo.setNgaySanXuat(simpleDateFormat.format(txtNgaySanXuat.getDate()));
        }else{
            JOptionPane.showMessageDialog(null, "Ngày sản xuất không được trống");
            txtNgaySanXuat.requestFocus();
            return;
        }
        
        //Hạn sử dụng
        if (txtHanSuDung.getDate() != null) {
            lo.setHanSuDung(simpleDateFormat.format(txtHanSuDung.getDate()));
        }else{
            JOptionPane.showMessageDialog(null, "Hạn sử dụng không được trống");
            txtHanSuDung.requestFocus();
            return;
        }
        
        //gia ban
        if (trangChuUI.checkReg(txtGiaBan.getText(), "\\d{1,11}")) {
            lo.setGiaBan(Integer.parseInt(txtGiaBan.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Giá bán không hợp lệ");
            txtGiaBan.requestFocus();
            return;
        }
        
        //so luong
        if (trangChuUI.checkReg(txtSoLuong.getText(), "\\d{1,11}")) {
            lo.setSoLuong(Integer.parseInt(txtSoLuong.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ");
            txtSoLuong.requestFocus();
            return;
        }
        
        //don gia von
        if (trangChuUI.checkReg(txtDonGiaVon.getText(), "\\d{1,11}")) {
            lo.setDonGiaVon(Integer.parseInt(txtDonGiaVon.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Đơn giá vốn không hợp lệ");
            txtDonGiaVon.requestFocus();
            return;
        }
        
        
        //Thuc hien them lo
        LoService loService = new LoService();
        int result = loService.themLo(lo);
        if (result>0) {
            hienThiToanBoLo();
            JOptionPane.showMessageDialog(null, "Đã thêm");
        }else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại. Vui lòng kiểm tra lại");
            return;
        }

    }//GEN-LAST:event_btbLuuActionPerformed
    
    public void hienThiSoChungTuNhap(){
        ArrayList<HoaDonNhap> dshoaDonNhap = null;
        HoaDonNhapService hoaDonNhapService  =new HoaDonNhapService();
        dshoaDonNhap = hoaDonNhapService.layToanToanBoHoaDon();
        cbSoChungTuNhap.removeAllItems();
        for (HoaDonNhap hoaDonNhap : dshoaDonNhap) {
            cbSoChungTuNhap.addItem(hoaDonNhap.getSoChungTuNhap()+"");
        }
    }
    
    public void hienThiSoChungTuNhapSua(){
        ArrayList<HoaDonNhap> dshoaDonNhap = null;
        HoaDonNhapService hoaDonNhapService  =new HoaDonNhapService();
        dshoaDonNhap = hoaDonNhapService.layToanToanBoHoaDon();
        for (HoaDonNhap hoaDonNhap : dshoaDonNhap) {
            cbSoChungTuNhapSua.addItem(hoaDonNhap.getSoChungTuNhap()+"");
        }
    }
    
    public void hienThiTenThuoc(){
        ArrayList<Thuoc> dsThuoc = null;
        ThuocService thuocService = new ThuocService();
        dsThuoc = thuocService.layToanBoThongTinThuoc();
        cbMaThuoc.removeAllItems();
        for (Thuoc thuoc : dsThuoc) {
            cbMaThuoc.addItem(thuoc.getMaThuoc() + "_"+thuoc.getTenThuoc());
        }
    }
    
    public void hienThiTenThuocSua(){
        ArrayList<Thuoc> dsThuoc = null;
        ThuocService thuocService = new ThuocService();
        dsThuoc = thuocService.layToanBoThongTinThuoc();
        for (Thuoc thuoc : dsThuoc) {
            cbMaThuocSua.addItem(thuoc.getMaThuoc() + "_"+thuoc.getTenThuoc());
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ThemLo.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btbCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCapNhatActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        
        Lo lo = new Lo();
        //Ma lo
        if (trangChuUI.checkDoDai(txtMaLoSua.getText(), 1, 5)) {
            
            lo.setMaLo(txtMaLoSua.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Mã lô không hợp lệ");
            return;
        }
        
        //So chung tu nhap
        lo.setSoChungTuNhap(Integer.parseInt(cbSoChungTuNhapSua.getSelectedItem().toString()));
        //Ma thuoc
        String maThuoc = trangChuUI.ngatChuoi(cbMaThuocSua.getSelectedItem().toString(), "_", 0);
        lo.setMaThuoc(maThuoc);
        //Ngay san xuat
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        lo.setNgaySanXuat(simpleDateFormat.format(txtNgaySanXuatSua.getDate()));
        //Han su dung
        lo.setHanSuDung(simpleDateFormat.format(txtHanSuDungSua.getDate()));
        //Gia ban
        if (trangChuUI.checkReg(txtGiaBanSua.getText(), "\\d{1,11}")) {
            
            lo.setGiaBan(Integer.parseInt(txtGiaBanSua.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Giá bán không hợp lệ");
            txtGiaBanSua.requestFocus();
            return;
        }
        //so luong
        if (trangChuUI.checkReg(txtSoLuongSua.getText(), "\\d{1,11}")) {
            lo.setSoLuong(Integer.parseInt(txtSoLuongSua.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Số lượng không hợp lệ");
            txtSoLuongSua.requestFocus();
            return;
        }
        //Don gia von
        if (trangChuUI.checkReg(txtDonGiaVonSua.getText(), "\\d{1,11}")) {
            lo.setDonGiaVon(Integer.parseInt(txtDonGiaVonSua.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Đơn giá vốn không hợp lệ");
            txtDonGiaVonSua.requestFocus();
            return;
        }
        
        LoService loService = new LoService();
        int result = loService.suaLo(lo);
        if (result > 0) {
            hienThiToanBoLo();
            JOptionPane.showMessageDialog(null, "Đã cập nhât");
        }else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại, Vui long kiểm tra lại");
        }
    }//GEN-LAST:event_btbCapNhatActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaLo;
    private javax.swing.JDialog ThemLo;
    private javax.swing.JButton btbCapNhat;
    private javax.swing.JButton btbLuu;
    private javax.swing.JButton btnSuaLo;
    private javax.swing.JButton btnThemLo;
    private javax.swing.JButton btnXoaLo;
    private javax.swing.JComboBox<String> cbMaThuoc;
    private javax.swing.JComboBox<String> cbMaThuocSua;
    private javax.swing.JComboBox<String> cbSoChungTuNhap;
    private javax.swing.JComboBox<String> cbSoChungTuNhapSua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbLo;
    private javax.swing.JTextField txtDonGiaVon;
    private javax.swing.JTextField txtDonGiaVonSua;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaBanSua;
    private com.toedter.calendar.JDateChooser txtHanSuDung;
    private com.toedter.calendar.JDateChooser txtHanSuDungSua;
    private javax.swing.JTextField txtMaLo;
    private javax.swing.JTextField txtMaLoSua;
    private com.toedter.calendar.JDateChooser txtNgaySanXuat;
    private com.toedter.calendar.JDateChooser txtNgaySanXuatSua;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoLuongSua;
    // End of variables declaration//GEN-END:variables
}
