/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.NhomThuoc;
import Service.NhanVienService;
import Service.NhomThuocService;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class NhomThuocUI extends javax.swing.JFrame {

    /**
     * Creates new form NhomThuocUI
     */
    ArrayList<NhomThuoc> dsNhomThuoc = null;
    public NhomThuocUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemNhomThuoc = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhomThuoc = new javax.swing.JTextField();
        btbLuuNhomThuoc = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        SuaNhomThuoc = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTenNhomThuocSua = new javax.swing.JTextField();
        txtMaNhomSua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCapNhat = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhomThuoc = new javax.swing.JTable();
        btnThemNhomThuoc = new javax.swing.JButton();
        btnSuaNhomThuoc = new javax.swing.JButton();
        btnXoaNhomThuoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        ThemNhomThuoc.setTitle("Thêm nhóm thuốc");
        ThemNhomThuoc.setSize(new java.awt.Dimension(380, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Tên nhóm thuốc:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btbLuuNhomThuoc.setBackground(new java.awt.Color(0, 153, 51));
        btbLuuNhomThuoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuuNhomThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btbLuuNhomThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuuNhomThuoc.setText("Lưu");
        btbLuuNhomThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuNhomThuocActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btbLuuNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnThoat))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuuNhomThuoc)
                    .addComponent(btnThoat))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemNhomThuocLayout = new javax.swing.GroupLayout(ThemNhomThuoc.getContentPane());
        ThemNhomThuoc.getContentPane().setLayout(ThemNhomThuocLayout);
        ThemNhomThuocLayout.setHorizontalGroup(
            ThemNhomThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ThemNhomThuocLayout.setVerticalGroup(
            ThemNhomThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaNhomThuoc.setSize(new java.awt.Dimension(380, 285));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tên nhóm thuốc:");

        jLabel4.setText("Mã nhóm:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(txtTenNhomThuocSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtMaNhomSua, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(42, 42, 42))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaNhomSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNhomThuocSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat1.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat1.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaNhomThuocLayout = new javax.swing.GroupLayout(SuaNhomThuoc.getContentPane());
        SuaNhomThuoc.getContentPane().setLayout(SuaNhomThuocLayout);
        SuaNhomThuocLayout.setHorizontalGroup(
            SuaNhomThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuaNhomThuocLayout.setVerticalGroup(
            SuaNhomThuocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản lí nhóm thuốc");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbNhomThuoc = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbNhomThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNhomThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhomThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhomThuoc);

        btnThemNhomThuoc.setBackground(new java.awt.Color(0, 153, 51));
        btnThemNhomThuoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemNhomThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhomThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemNhomThuoc.setText("Thêm");
        btnThemNhomThuoc.setToolTipText("");
        btnThemNhomThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhomThuocActionPerformed(evt);
            }
        });

        btnSuaNhomThuoc.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaNhomThuoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaNhomThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaNhomThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaNhomThuoc.setText("Sửa");
        btnSuaNhomThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhomThuocActionPerformed(evt);
            }
        });

        btnXoaNhomThuoc.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaNhomThuoc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaNhomThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNhomThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaNhomThuoc.setText("Xóa");
        btnXoaNhomThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhomThuocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách nhóm thuốc");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnThemNhomThuoc)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaNhomThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNhomThuoc)
                    .addComponent(btnSuaNhomThuoc)
                    .addComponent(btnXoaNhomThuoc))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Vector<Object> header = new Vector<>();
    Vector<Object> data  = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Mã nhóm");
        header.add("Tên nhóm thuốc");
     
        model = (DefaultTableModel) tbNhomThuoc.getModel();    
        model.setDataVector(data, header);
    }
    
    public void hienThiToanBoNhomThuoc(){
        
        NhomThuocService nhomThuocService = new NhomThuocService();
        dsNhomThuoc = nhomThuocService.layToanBoNhomThuoc();
        
        model.setRowCount(0);
        for (NhomThuoc nhomThuoc : dsNhomThuoc) {
            Vector row = new Vector();
            row.add(nhomThuoc.getMaNhom());
            row.add(nhomThuoc.getTenNhom());
            data.add(row);
        }
        
    }
    
    
    
    private void btnThemNhomThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhomThuocActionPerformed
        // TODO add your handling code here:
        ThemNhomThuoc.setVisible(true);
        ThemNhomThuoc.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnThemNhomThuocActionPerformed

    private void btnSuaNhomThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhomThuocActionPerformed
        // TODO add your handling code here:
        if (maNhom == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn nhóm thuốc");
            return;
        }
        SuaNhomThuoc.setVisible(true);
        SuaNhomThuoc.setLocationRelativeTo(null);
        txtMaNhomSua.disable();
        
        
    }//GEN-LAST:event_btnSuaNhomThuocActionPerformed

    private void btnXoaNhomThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhomThuocActionPerformed
        // TODO add your handling code here:
        if (maNhom == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn nhóm thuốc cần xóa");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        NhomThuoc nhomThuoc = new NhomThuoc();
        nhomThuoc.setMaNhom(Integer.parseInt(maNhom));
        NhomThuocService nhomThuocService = new NhomThuocService();
        int result = nhomThuocService.xoaNhomThuoc(nhomThuoc);
        if (result > 0) {
            hienThiToanBoNhomThuoc();
            JOptionPane.showMessageDialog(null, "Đã xóa");
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }

    }//GEN-LAST:event_btnXoaNhomThuocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DanhMucThuocVaBenhUI danhMucThuocVaBenhUI = new DanhMucThuocVaBenhUI();
        danhMucThuocVaBenhUI.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuNhomThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuNhomThuocActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        NhomThuoc nhomThuoc = new NhomThuoc();
       
        if (trangChuUI.checkDoDai(txtTenNhomThuoc.getText(), 1, 50)) {
            nhomThuoc.setTenNhom(txtTenNhomThuoc.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Tên nhóm thuốc không hợp lệ");
            txtTenNhomThuoc.requestFocus();
            return;
        }
       
       NhomThuocService nhomThuocService = new NhomThuocService();
       int result = nhomThuocService.themNhomThuoc(nhomThuoc);
        if (result > 0) {
            hienThiToanBoNhomThuoc();
            JOptionPane.showMessageDialog(null, "Thêm thành công");
        }else{
            JOptionPane.showMessageDialog(null, "Nhóm thuốc đã tồn tài. Vui lòng kiêm tra lại");
            return;
        }
               

    }//GEN-LAST:event_btbLuuNhomThuocActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        ThemNhomThuoc.dispose();
      
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        TrangChuUI trangChuUI = new TrangChuUI();
        NhomThuoc nhomThuoc = new NhomThuoc();
        nhomThuoc.setMaNhom(Integer.parseInt(maNhom));
        
        if (trangChuUI.checkDoDai(txtTenNhomThuocSua.getText(), 1, 50)) {
            
            nhomThuoc.setTenNhom(txtTenNhomThuocSua.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Tên nhóm thuốc không hợp lệ");
            return; 
        }
        
        NhomThuocService nhomThuocService = new NhomThuocService();
        int result = nhomThuocService.suaNhomThuoc(nhomThuoc);
        if (result > 0) {
            hienThiToanBoNhomThuoc();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Nhóm thuốc đã tồn tại. Vui lòng kiêm tra lại");
            return;
                   
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        // TODO add your handling code here:
        SuaNhomThuoc.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed
    String maNhom;
    private void tbNhomThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhomThuocMouseClicked
        // TODO add your handling code here:
        int row = tbNhomThuoc.getSelectedRow();
        maNhom = tbNhomThuoc.getValueAt(row, 0).toString();
        String tenNhom = tbNhomThuoc.getValueAt(row, 1).toString();
        
        txtMaNhomSua.setText(maNhom);
        txtTenNhomThuocSua.setText(tenNhom);
    }//GEN-LAST:event_tbNhomThuocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhomThuocUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhomThuocUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhomThuocUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhomThuocUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhomThuocUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaNhomThuoc;
    private javax.swing.JDialog ThemNhomThuoc;
    private javax.swing.JButton btbLuuNhomThuoc;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSuaNhomThuoc;
    private javax.swing.JButton btnThemNhomThuoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXoaNhomThuoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNhomThuoc;
    private javax.swing.JTextField txtMaNhomSua;
    private javax.swing.JTextField txtTenNhomThuoc;
    private javax.swing.JTextField txtTenNhomThuocSua;
    // End of variables declaration//GEN-END:variables
}
