/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.HoaDonNhap;
import Model.NhanVien;
import Service.HoaDonNhapService;
import java.awt.Toolkit;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class HoaDonNhapUI extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonNhapUI
     */
    
    
    DefaultTableModel model;
    public HoaDonNhapUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemHoaDonNhap = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTenNhaCungCap = new javax.swing.JTextField();
        txtTongTienNhap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayGioNhap = new com.toedter.calendar.JDateChooser();
        btbLuuHoaDonNhap = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SuaHoaDonNhap = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTenNhaCungCapSua = new javax.swing.JTextField();
        txtTongTienNhapSua = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoChungTuSua = new javax.swing.JTextField();
        txtNgayGioNhapSua = new com.toedter.calendar.JDateChooser();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDonNhapThuoc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThemHoaDonNhap = new javax.swing.JButton();
        btnSuaHoaDonNhap = new javax.swing.JButton();
        btnXoaHoaDonNhap = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        ThemHoaDonNhap.setSize(new java.awt.Dimension(555, 410));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Hóa đơn nhập"));
        jPanel2.setToolTipText("");

        jLabel4.setText("Tên nhà cung cấp");

        jLabel8.setText("Tổng tiền nhập");

        jLabel2.setText("VNĐ");

        jLabel3.setText("Ngày giờ nhập");

        txtNgayGioNhap.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtTenNhaCungCap)
                    .addComponent(txtNgayGioNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayGioNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTongTienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        btbLuuHoaDonNhap.setBackground(new java.awt.Color(0, 153, 51));
        btbLuuHoaDonNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuuHoaDonNhap.setForeground(new java.awt.Color(255, 255, 255));
        btbLuuHoaDonNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuuHoaDonNhap.setText("Lưu");
        btbLuuHoaDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuHoaDonNhapActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btbLuuHoaDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuuHoaDonNhap)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemHoaDonNhapLayout = new javax.swing.GroupLayout(ThemHoaDonNhap.getContentPane());
        ThemHoaDonNhap.getContentPane().setLayout(ThemHoaDonNhapLayout);
        ThemHoaDonNhapLayout.setHorizontalGroup(
            ThemHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThemHoaDonNhapLayout.setVerticalGroup(
            ThemHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaHoaDonNhap.setSize(new java.awt.Dimension(655, 410));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Sửa hóa đơn nhập"));
        jPanel3.setToolTipText("");

        jLabel5.setText("Tên nhà cung cấp");

        jLabel9.setText("Tổng tiền nhập");

        jLabel6.setText("VNĐ");

        jLabel7.setText("Ngày giờ nhập");

        jLabel10.setText("Số chứng từ nhập");

        txtNgayGioNhapSua.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienNhapSua, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtTenNhaCungCapSua)
                    .addComponent(txtSoChungTuSua)
                    .addComponent(txtNgayGioNhapSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoChungTuSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayGioNhapSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenNhaCungCapSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongTienNhapSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30))
        );

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaHoaDonNhapLayout = new javax.swing.GroupLayout(SuaHoaDonNhap.getContentPane());
        SuaHoaDonNhap.getContentPane().setLayout(SuaHoaDonNhapLayout);
        SuaHoaDonNhapLayout.setHorizontalGroup(
            SuaHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuaHoaDonNhapLayout.setVerticalGroup(
            SuaHoaDonNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbHoaDonNhapThuoc = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbHoaDonNhapThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDonNhapThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonNhapThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDonNhapThuoc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách hóa đơn nhập thuốc");

        btnThemHoaDonNhap.setBackground(new java.awt.Color(0, 153, 51));
        btnThemHoaDonNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemHoaDonNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHoaDonNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemHoaDonNhap.setText("Thêm");
        btnThemHoaDonNhap.setToolTipText("");
        btnThemHoaDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonNhapActionPerformed(evt);
            }
        });

        btnSuaHoaDonNhap.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaHoaDonNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaHoaDonNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaHoaDonNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaHoaDonNhap.setText("Sửa");
        btnSuaHoaDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHoaDonNhapActionPerformed(evt);
            }
        });

        btnXoaHoaDonNhap.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaHoaDonNhap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaHoaDonNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaHoaDonNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaHoaDonNhap.setText("Xóa");
        btnXoaHoaDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonNhapActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(btnThemHoaDonNhap)
                .addGap(18, 18, 18)
                .addComponent(btnSuaHoaDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaHoaDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemHoaDonNhap)
                    .addComponent(btnSuaHoaDonNhap)
                    .addComponent(btnXoaHoaDonNhap))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Set table hoa don nhap
    //vec to tao bang
    Vector<Object> header = new Vector<>();
    Vector<Object> data = new Vector<>();
    private void setTable(){
        header.add("Số chứng từ nhập");
        header.add("Nhân viên nhập");
        header.add("Ngày giờ nhập");
        header.add("Tên nhà cung cấp");
        header.add("Tổng số tiền (VNĐ)");
        model = (DefaultTableModel) tbHoaDonNhapThuoc.getModel();
        model.setDataVector(data, header);
    }
    
    //hien thi toan bo hoa don nhap
    ArrayList<HoaDonNhap> dsHoaDonNhap = null;
    public void hienThiToanBoHoaDonNhap(){
        HoaDonNhapService hoaDonNhapService = new HoaDonNhapService();
        dsHoaDonNhap = hoaDonNhapService.layToanToanBoHoaDon();
        
        model.setRowCount(0);
        //fotmat number 
        NumberFormat currentLocale = NumberFormat.getInstance();
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);
        
        for (HoaDonNhap hoaDonNhap : dsHoaDonNhap) {
            Vector row = new Vector();
            row.add(hoaDonNhap.getSoChungTuNhap());
            row.add(hoaDonNhap.getHo()+" "+hoaDonNhap.getTen());
            row.add(hoaDonNhap.getNgayGioNhap());
            row.add(hoaDonNhap.getTenNhaCungCap());
            row.add(vn.format(hoaDonNhap.getTongTienNhap()));
            data.add(row);
        }
    }
    
    
    
    private void btnThemHoaDonNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHoaDonNhapActionPerformed
        // TODO add your handling code here:
        ThemHoaDonNhap.setVisible(true);
        ThemHoaDonNhap.setLocationRelativeTo(null);
        //Khong cho nhap ngay thang
        txtNgayGioNhap.getDateEditor().setEnabled(false);
        
    }//GEN-LAST:event_btnThemHoaDonNhapActionPerformed

    private void btnSuaHoaDonNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHoaDonNhapActionPerformed
        //check btn sua
        if (soChungTuNhap == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hóa đơn");
            return;
        }
        
        SuaHoaDonNhap.setVisible(true);
        SuaHoaDonNhap.setLocationRelativeTo(null);
        //khong cho nhap ngay thang
        txtNgayGioNhapSua.getDateEditor().setEnabled(false);
    }//GEN-LAST:event_btnSuaHoaDonNhapActionPerformed

    private void btnXoaHoaDonNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonNhapActionPerformed
        // TODO add your handling code here:
        if (soChungTuNhap == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hóa đơn cần xóa");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, "Ban chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            //Thuc hien hoa
            HoaDonNhap hoaDonNhap = new HoaDonNhap();
            hoaDonNhap.setSoChungTuNhap(Integer.parseInt(soChungTuNhap));
            HoaDonNhapService hoaDonNhapService = new HoaDonNhapService();
            
            int result = hoaDonNhapService.xoaHoaDon(hoaDonNhap);
            if (result > 0) {
                hienThiToanBoHoaDonNhap();
                JOptionPane.showMessageDialog(null, "Đã xóa");
            }else{
               JOptionPane.showMessageDialog(null, "Hóa đơn đang được sử dụng không thể xóa. Vui lòng kiểm tra lại");
               return;
            }
        }else{
            
            return;
        }        
        
    }//GEN-LAST:event_btnXoaHoaDonNhapActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NhapThuocUI nhapThuocUI = new NhapThuocUI();
        nhapThuocUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuHoaDonNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuHoaDonNhapActionPerformed
        //Lay ma nhan vien
        TrangChuUI trangChuUI = new TrangChuUI();
        trangChuUI.layThongTinNhanVien();
        int maNV = trangChuUI.maNV;
        
        HoaDonNhap hoaDonNhap = new HoaDonNhap();
        
        //ma nhan vien
        hoaDonNhap.setMaNhanVien(maNV);
        
        //check thoi gian nhap
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (txtNgayGioNhap.getDate()!= null){
            hoaDonNhap.setNgayGioNhap(simpleDateFormat.format(txtNgayGioNhap.getDate()));
        }else{
            JOptionPane.showMessageDialog(null, "Thời gian nhập không hơp lệ.");
            return;
        }
        
        //check ten nha cung cap
        if (trangChuUI.checkDoDai(txtTenNhaCungCap.getText(),2 ,200)) {
            hoaDonNhap.setTenNhaCungCap(txtTenNhaCungCap.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Tên nhà cung cấp phải có độ dài từ 2 - 50 ký tự");
            txtTenNhaCungCap.requestFocus();
            return;
        }
        
        //check hoa don nhap
        if (trangChuUI.checkReg(txtTongTienNhap.getText(), "\\d{3,10}")) {
            hoaDonNhap.setTongTienNhap(Integer.parseInt(txtTongTienNhap.getText().trim()));            
        }else{
            JOptionPane.showMessageDialog(null, "Tổng tiền nhập phải là số dộ dài từ 3-10");
            txtTongTienNhap.requestFocus();
            return;
        }
        
        //Thuc hien them hoa don
        HoaDonNhapService hoaDonNhapService = new HoaDonNhapService();
        int result = hoaDonNhapService.themHoaDonNhap(hoaDonNhap);
        if (result>0) {
            hienThiToanBoHoaDonNhap();
            JOptionPane.showMessageDialog(null, "Đã thêm một hóa đơn");
        }else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại. Vui lòng kiểm tra lại");
            return;
        }
        
    }//GEN-LAST:event_btbLuuHoaDonNhapActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ThemHoaDonNhap.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
         //Lay ma nhan vien
        TrangChuUI trangChuUI = new TrangChuUI();
        HoaDonNhap hoaDonNhap = new HoaDonNhap();
        
        //So chung tu nhap
        hoaDonNhap.setSoChungTuNhap(Integer.parseInt(soChungTuNhap));
        
        //check thoi gian nhap
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (txtNgayGioNhapSua.getDate()!= null){
            hoaDonNhap.setNgayGioNhap(simpleDateFormat.format(txtNgayGioNhapSua.getDate()));
        }else if (txtNgayGioNhapSua.getDate() == null) {
            //lay gio he thong
        }else{
            JOptionPane.showMessageDialog(null, "Thời gian nhập không hơp lệ.");
            return;
        }
        
        //check ten nha cung cap
        if (trangChuUI.checkDoDai(txtTenNhaCungCapSua.getText(),2 ,200)) {
            hoaDonNhap.setTenNhaCungCap(txtTenNhaCungCapSua.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Tên nhà cung cấp phải có độ dài từ 2 - 50 ký tự");
            txtTenNhaCungCapSua.requestFocus();
            return;
        }
        
        //check hoa don nhap
        if (trangChuUI.checkReg(txtTongTienNhapSua.getText(), "\\d{3,10}")) {
            hoaDonNhap.setTongTienNhap(Integer.parseInt(txtTongTienNhapSua.getText().trim()));            
        }else{
            JOptionPane.showMessageDialog(null, "Tổng tiền nhập phải là số dộ dài từ 3-10");
            txtTongTienNhapSua.requestFocus();
            return;
        }
        
        //thuc hien cap nhat
        HoaDonNhapService hoaDonNhapService = new HoaDonNhapService();
        int result = hoaDonNhapService.suaHoaDonNhap(hoaDonNhap);
        if (result>0) {
            hienThiToanBoHoaDonNhap();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
            return;
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        SuaHoaDonNhap.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    String soChungTuNhap;
    private void tbHoaDonNhapThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonNhapThuocMouseClicked
        // TODO add your handling code here:
        int row = tbHoaDonNhapThuoc.getSelectedRow();
        soChungTuNhap = tbHoaDonNhapThuoc.getValueAt(row, 0).toString();
        
        //Ngay gio nhap
        try {
            Date ngayGioNhap = new SimpleDateFormat("yyyy-MM-dd").parse(tbHoaDonNhapThuoc.getValueAt(row, 2).toString());
            txtNgayGioNhapSua.setDate(ngayGioNhap);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonNhapUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String tenNhaCungCap = (String) tbHoaDonNhapThuoc.getValueAt(row, 3);
        String tongTien = tbHoaDonNhapThuoc.getValueAt(row, 4).toString();
        
        //hien thi len form sua
        txtSoChungTuSua.setText(soChungTuNhap);
        txtSoChungTuSua.disable();
        txtTenNhaCungCapSua.setText(tenNhaCungCap);
        txtTongTienNhapSua.setText(tongTien.replace(".", ""));
    }//GEN-LAST:event_tbHoaDonNhapThuocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonNhapUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SuaHoaDonNhap;
    private javax.swing.JDialog ThemHoaDonNhap;
    private javax.swing.JButton btbLuuHoaDonNhap;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnSuaHoaDonNhap;
    private javax.swing.JButton btnThemHoaDonNhap;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaHoaDonNhap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHoaDonNhapThuoc;
    private com.toedter.calendar.JDateChooser txtNgayGioNhap;
    private com.toedter.calendar.JDateChooser txtNgayGioNhapSua;
    private javax.swing.JTextField txtSoChungTuSua;
    private javax.swing.JTextField txtTenNhaCungCap;
    private javax.swing.JTextField txtTenNhaCungCapSua;
    private javax.swing.JTextField txtTongTienNhap;
    private javax.swing.JTextField txtTongTienNhapSua;
    // End of variables declaration//GEN-END:variables
}
