/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.ChiTietHoaDonXuat;
import Model.HoaDonNhap;
import Model.HoaDonXuat;
import Model.InHoaDonXuat;
import Model.Lo;
import Model.Thuoc;
import Service.ChiTietHoaDonXuatService;
import Service.HoaDonNhapService;
import Service.HoaDonXuatService;
import Service.InHoaDonXuatService;
import Service.LoService;
import Service.ThuocService;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danhx
 */
public class HoaDonXuatUI extends javax.swing.JFrame {

    /**
     * Creates new form HoaDonXuatUI
     */
    public HoaDonXuatUI() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon\\capsule.png")));
        setTable();
        setTableInHoaDon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemHoaDonXuat = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTongTienXuat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNgayGioXuat = new com.toedter.calendar.JDateChooser();
        btbLuuHoaDonXuat = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SuaHoaDonXuat = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTongTienXuatSua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSoChungTuSua = new javax.swing.JTextField();
        txtNgayGioXuatSua = new com.toedter.calendar.JDateChooser();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        InHoaDon = new javax.swing.JDialog();
        pnInHoaDon = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbInHoaDon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblSoChungTuXuat = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblNgayGioXuat = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDocThanhChu = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDonXuatThuoc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnThemHoaDonXuat = new javax.swing.JButton();
        btnSuaHoaDonXuat = new javax.swing.JButton();
        btnXoaHoaDonXuat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();

        ThemHoaDonXuat.setSize(new java.awt.Dimension(555, 320));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Thông tin hóa đơn"));
        jPanel2.setToolTipText("");

        txtTongTienXuat.setText("000");

        jLabel8.setText("Tổng tiền xuất");

        jLabel2.setText("VNĐ");

        jLabel3.setText("Ngày giờ xuất");

        txtNgayGioXuat.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtNgayGioXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNgayGioXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btbLuuHoaDonXuat.setBackground(new java.awt.Color(0, 153, 51));
        btbLuuHoaDonXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbLuuHoaDonXuat.setForeground(new java.awt.Color(255, 255, 255));
        btbLuuHoaDonXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btbLuuHoaDonXuat.setText("Tạo hóa đơn");
        btbLuuHoaDonXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbLuuHoaDonXuatActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btbLuuHoaDonXuat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbLuuHoaDonXuat)
                    .addComponent(jButton5))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemHoaDonXuatLayout = new javax.swing.GroupLayout(ThemHoaDonXuat.getContentPane());
        ThemHoaDonXuat.getContentPane().setLayout(ThemHoaDonXuatLayout);
        ThemHoaDonXuatLayout.setHorizontalGroup(
            ThemHoaDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ThemHoaDonXuatLayout.setVerticalGroup(
            ThemHoaDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SuaHoaDonXuat.setSize(new java.awt.Dimension(555, 390));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Sửa hóa đơn xuất"));
        jPanel3.setToolTipText("");

        jLabel9.setText("Tổng tiền nhập");

        jLabel6.setText("VNĐ");

        jLabel7.setText("Ngày giờ nhập");

        jLabel10.setText("Số chứng từ nhập");

        txtNgayGioXuatSua.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienXuatSua)
                    .addComponent(txtSoChungTuSua)
                    .addComponent(txtNgayGioXuatSua, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoChungTuSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayGioXuatSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienXuatSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addGap(62, 62, 62))
        );

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 51));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/floppy-disk-save-button.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 51, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/cancel-button.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnCapNhat)
                        .addGap(208, 208, 208)
                        .addComponent(btnThoat)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat)
                    .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuaHoaDonXuatLayout = new javax.swing.GroupLayout(SuaHoaDonXuat.getContentPane());
        SuaHoaDonXuat.getContentPane().setLayout(SuaHoaDonXuatLayout);
        SuaHoaDonXuatLayout.setHorizontalGroup(
            SuaHoaDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SuaHoaDonXuatLayout.setVerticalGroup(
            SuaHoaDonXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        InHoaDon.setTitle("In hóa đơn");
        InHoaDon.setSize(new java.awt.Dimension(325, 580));

        pnInHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        tbInHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbInHoaDon.setEnabled(false);
        jScrollPane3.setViewportView(tbInHoaDon);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/pillsHoaDon.png"))); // NOI18N
        jLabel4.setText("Hóa đơn xuất");

        lblSoChungTuXuat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblSoChungTuXuat.setText("Số hóa đơn: ");

        lblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblNhanVien.setText("Nhân viên: ");

        lblNgayGioXuat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblNgayGioXuat.setText("Ngày lập: ");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongTien.setText("Tổng tiền: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Chi tiết hóa đơn");

        txtDocThanhChu.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txtDocThanhChu.setText("Doc thanh chu");

        javax.swing.GroupLayout pnInHoaDonLayout = new javax.swing.GroupLayout(pnInHoaDon);
        pnInHoaDon.setLayout(pnInHoaDonLayout);
        pnInHoaDonLayout.setHorizontalGroup(
            pnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInHoaDonLayout.createSequentialGroup()
                .addGroup(pnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNgayGioXuat))
                    .addComponent(lblNhanVien)
                    .addGroup(pnInHoaDonLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5))
                    .addGroup(pnInHoaDonLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblTongTien)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoChungTuXuat)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInHoaDonLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnInHoaDonLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(txtDocThanhChu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnInHoaDonLayout.setVerticalGroup(
            pnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnInHoaDonLayout.createSequentialGroup()
                .addGroup(pnInHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoChungTuXuat)
                    .addGroup(pnInHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(2, 2, 2)
                .addComponent(lblNgayGioXuat)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTongTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDocThanhChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblNhanVien))
        );

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Thực hiện in");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InHoaDonLayout = new javax.swing.GroupLayout(InHoaDon.getContentPane());
        InHoaDon.getContentPane().setLayout(InHoaDonLayout);
        InHoaDonLayout.setHorizontalGroup(
            InHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap())
        );
        InHoaDonLayout.setVerticalGroup(
            InHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InHoaDonLayout.createSequentialGroup()
                .addComponent(pnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản lí hóa đơn xuất");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbHoaDonXuatThuoc = new javax.swing.JTable () {
            public boolean isCellEditable (int rowIndex, int colIndex) {
                return false; // Không cho phép chỉnh sửa bất kỳ ô nào
            }
        };
        tbHoaDonXuatThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHoaDonXuatThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonXuatThuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDonXuatThuoc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Danh sách hóa đơn xuất thuốc");

        btnThemHoaDonXuat.setBackground(new java.awt.Color(0, 153, 51));
        btnThemHoaDonXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnThemHoaDonXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHoaDonXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/add.png"))); // NOI18N
        btnThemHoaDonXuat.setText("Thêm");
        btnThemHoaDonXuat.setToolTipText("");
        btnThemHoaDonXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHoaDonXuatActionPerformed(evt);
            }
        });

        btnSuaHoaDonXuat.setBackground(new java.awt.Color(255, 204, 0));
        btnSuaHoaDonXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSuaHoaDonXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaHoaDonXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/refresh-button.png"))); // NOI18N
        btnSuaHoaDonXuat.setText("Sửa");
        btnSuaHoaDonXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHoaDonXuatActionPerformed(evt);
            }
        });

        btnXoaHoaDonXuat.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaHoaDonXuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnXoaHoaDonXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaHoaDonXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/round-delete-button.png"))); // NOI18N
        btnXoaHoaDonXuat.setText("Xóa");
        btnXoaHoaDonXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonXuatActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/left-arrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnIn.setBackground(new java.awt.Color(0, 102, 204));
        btnIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIn.setForeground(new java.awt.Color(255, 255, 255));
        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Icon/print.png"))); // NOI18N
        btnIn.setText("In");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemHoaDonXuat)
                .addGap(18, 18, 18)
                .addComponent(btnSuaHoaDonXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaHoaDonXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaHoaDonXuat)
                    .addComponent(btnXoaHoaDonXuat)
                    .addComponent(btnThemHoaDonXuat)
                    .addComponent(btnIn))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //vec to tao bang
    Vector<Object> header = new Vector<>();
    Vector<Object> data = new Vector<>();
    DefaultTableModel model;
    private void setTable(){
        header.add("Số chứng từ xuất");
        header.add("Nhân viên xuất");
        header.add("Ngày giờ xuất");
        header.add("Tổng tiền bán(VNĐ)");
        model = (DefaultTableModel) tbHoaDonXuatThuoc.getModel();
        model.setDataVector(data, header);
    }

    //hien thi toan bo hoa don nhap
    ArrayList<HoaDonXuat> dsHoaDonXuat = null;
    public void hienThiToanBoHoaDonXuat(){
        HoaDonXuatService hoaDonXuatService = new HoaDonXuatService();
        dsHoaDonXuat = hoaDonXuatService.layToanToanBoHoaXuat();

        model.setRowCount(0);
        //fotmat number
        NumberFormat currentLocale = NumberFormat.getInstance();
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat vn = NumberFormat.getInstance(localeVN);

        for (HoaDonXuat hoaDonXuat : dsHoaDonXuat) {
            Vector row = new Vector();
            row.add(hoaDonXuat.getSoChungTuXuat());
            row.add(hoaDonXuat.getHo()+" "+hoaDonXuat.getTen());
            row.add(hoaDonXuat.getNgayGioXuat());
            row.add(vn.format(hoaDonXuat.getTongTienBan()));
            data.add(row);
        }
    }

   


    String soChungTuXuat;
    private void tbHoaDonXuatThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonXuatThuocMouseClicked
        // TODO add your handling code here:
        int row = tbHoaDonXuatThuoc.getSelectedRow();
        soChungTuXuat = tbHoaDonXuatThuoc.getValueAt(row, 0).toString();

        //Ngay gio nhap
        try {
            Date ngayGioxuat = new SimpleDateFormat("yyyy-MM-dd").parse(tbHoaDonXuatThuoc.getValueAt(row, 2).toString());
            txtNgayGioXuatSua.setDate(ngayGioxuat);
        } catch (ParseException ex) {
            Logger.getLogger(HoaDonNhapUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        String tongTien = tbHoaDonXuatThuoc.getValueAt(row, 3).toString();

        //hien thi len form sua
        txtSoChungTuSua.setText(soChungTuXuat);
        txtSoChungTuSua.disable();
        txtTongTienXuatSua.setText(tongTien.replace(".", ""));
    }//GEN-LAST:event_tbHoaDonXuatThuocMouseClicked

    private void btnThemHoaDonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHoaDonXuatActionPerformed
        // TODO add your handling code here:
        ThemHoaDonXuat.setVisible(true);
        ThemHoaDonXuat.setLocationRelativeTo(null);
        //Khong cho nhap ngay thang
        txtNgayGioXuat.getDateEditor().setEnabled(false);
        txtTongTienXuat.disable();
    }//GEN-LAST:event_btnThemHoaDonXuatActionPerformed

    private void btnSuaHoaDonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHoaDonXuatActionPerformed
        //check btn sua
        if (soChungTuXuat == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hóa đơn");
            return;
        }

        SuaHoaDonXuat.setVisible(true);
        SuaHoaDonXuat.setLocationRelativeTo(null);
        //khong cho nhap ngay thang
        txtNgayGioXuatSua.getDateEditor().setEnabled(false);
        
        
    }//GEN-LAST:event_btnSuaHoaDonXuatActionPerformed

    private void btnXoaHoaDonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonXuatActionPerformed
        // TODO add your handling code here:
        if (soChungTuXuat == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hóa đơn cần xóa");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "Ban chắc chắn muốn xóa?", "Xác nhận", JOptionPane.YES_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {

            //Thuc hien hoa
            HoaDonXuat hoaDonXuat = new HoaDonXuat();
            hoaDonXuat.setSoChungTuXuat(Integer.parseInt(soChungTuXuat));
            HoaDonXuatService hoaDonXuatService = new HoaDonXuatService();

            int result = hoaDonXuatService.xoaHoaDon(hoaDonXuat);
            if (result > 0) {
                hienThiToanBoHoaDonXuat();
                JOptionPane.showMessageDialog(null, "Đã xóa");
            }else{
                JOptionPane.showMessageDialog(null, "Hóa đơn đang được sử dụng không thể xóa, Vui lòng kiểm tra lại");
                return;
            }
        }else{
            return;
        }

    }//GEN-LAST:event_btnXoaHoaDonXuatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        XuatThuocUI xuatThuocUI = new XuatThuocUI();
        xuatThuocUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbLuuHoaDonXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbLuuHoaDonXuatActionPerformed
        //Lay ma nhan vien
        TrangChuUI trangChuUI = new TrangChuUI();
        trangChuUI.layThongTinNhanVien();
        int maNV = trangChuUI.maNV;

        HoaDonXuat hoaDonXuat = new HoaDonXuat();

        //ma nhan vien
        hoaDonXuat.setMaNhanVien(maNV);

        //check thoi gian nhap
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (txtNgayGioXuat.getDate()!= null){
            hoaDonXuat.setNgayGioXuat(simpleDateFormat.format(txtNgayGioXuat.getDate()));
        }else{
            JOptionPane.showMessageDialog(null, "Thời gian nhập không hơp lệ.");
            return;
        }

        //check hoa don nhap
        if (trangChuUI.checkReg(txtTongTienXuat.getText(), "\\d{3,10}")) {
            hoaDonXuat.setTongTienBan(Integer.parseInt(txtTongTienXuat.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Tổng tiền nhập phải là số dộ dài từ 3-10");
            txtTongTienXuat.requestFocus();
            return;
        }

        //Thuc hien them hoa don
        HoaDonXuatService hoaDonXuatService = new HoaDonXuatService();
        int result = hoaDonXuatService.themHoaDonXuat(hoaDonXuat);
        if (result>0) {
            hienThiToanBoHoaDonXuat();
            JOptionPane.showMessageDialog(null, "Hóa đơn đã được tạo, Vui lòng thêm chi tiết cho hóa đơn!");
        }else{
            JOptionPane.showMessageDialog(null, "Tạo hóa đơn thất bại. Vui lòng kiểm tra lại");
            return;
        }

    }//GEN-LAST:event_btbLuuHoaDonXuatActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ThemHoaDonXuat.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        //Lay ma nhan vien
        TrangChuUI trangChuUI = new TrangChuUI();
        HoaDonXuat hoaDonXuat = new HoaDonXuat();

        //So chung tu nhap
        hoaDonXuat.setSoChungTuXuat(Integer.parseInt(soChungTuXuat));

        //check thoi gian nhap
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        if (txtNgayGioXuatSua.getDate()!= null){
            hoaDonXuat.setNgayGioXuat(simpleDateFormat.format(txtNgayGioXuatSua.getDate()));
        }else if (txtNgayGioXuatSua.getDate() == null) {
            //lay gio he thong
        }else{
            JOptionPane.showMessageDialog(null, "Thời gian xuất không hơp lệ.");
            return;
        }


        //check hoa don nhap
        if (trangChuUI.checkReg(txtTongTienXuatSua.getText(), "\\d{3,10}")) {
            hoaDonXuat.setTongTienBan(Integer.parseInt(txtTongTienXuatSua.getText().trim()));
        }else{
            JOptionPane.showMessageDialog(null, "Tổng tiền nhập phải là số dộ dài từ 3-10");
            txtTongTienXuatSua.requestFocus();
            return;
        }

        //thuc hien cap nhat
        HoaDonXuatService hoaDonXuatService = new HoaDonXuatService();
        int result = hoaDonXuatService.suaHoaDonXuat(hoaDonXuat);
        if (result>0) {
            hienThiToanBoHoaDonXuat();
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
        }else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
            return;
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:        
        SuaHoaDonXuat.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    Vector<Object> headerIn = new Vector<>();
    Vector<Object> dataIn = new Vector<>();
    DefaultTableModel modelIn;
    private void setTableInHoaDon(){
       
        headerIn.add("Tên thuốc");
        headerIn.add("Số lượng");
        headerIn.add("Giá (VNĐ)");
        
        modelIn = (DefaultTableModel) tbInHoaDon.getModel();
        modelIn.setDataVector(dataIn, headerIn);
    }
    
    
    ArrayList<InHoaDonXuat> dsInHoaDonXuat=null;
        
    public void hienThiInHoaDon(){
        
            HoaDonXuat hoaDonXuat  = new HoaDonXuat();
            hoaDonXuat.setSoChungTuXuat(Integer.parseInt(soChungTuXuat));
            
            InHoaDonXuatService inHoaDonXuatService = new InHoaDonXuatService();
            dsInHoaDonXuat = inHoaDonXuatService.layThongTinInHoaDonXuat(hoaDonXuat);
            
             //fotmat number 
            NumberFormat currentLocale = NumberFormat.getInstance();
            Locale localeVN = new Locale("vi", "VN");
            NumberFormat vn = NumberFormat.getInstance(localeVN);
            
            modelIn.setRowCount(0);
            int soChungTuXuatIn=0;
            String ngayGioXuatIn = null;
            String hoIn = null;
            String tenIn = null;
            int tongTienbanIn = 0;
            
            for (InHoaDonXuat inHoaDonXuat : dsInHoaDonXuat) {
                soChungTuXuatIn = inHoaDonXuat.getSoChungTuXuat();
                hoIn = inHoaDonXuat.getHo();
                tenIn = inHoaDonXuat.getTen();
                tongTienbanIn = inHoaDonXuat.getTongTienban();
                ngayGioXuatIn = inHoaDonXuat.getNgayGioXuat();
                
                Vector row = new Vector<Object>();
                row.add(inHoaDonXuat.getTenThuoc());
                row.add(inHoaDonXuat.getSoLuong());
                row.add(vn.format(inHoaDonXuat.getGiaBanDuaVaoSoLuong()));
                dataIn.add(row);
            }
            lblSoChungTuXuat.setText("Số hóa đơn: "+soChungTuXuatIn);
            lblNhanVien.setText("Nhân viên: "+hoIn+" "+tenIn);
            lblNgayGioXuat.setText("Ngày lập: " + ngayGioXuatIn);
            lblTongTien.setText("Tổng tiền: " + vn.format(tongTienbanIn)+" VNĐ");
            TrangChuUI trangChuUI = new TrangChuUI();
            String strTongTienBan = tongTienbanIn+"";
            ArrayList<String> kq = trangChuUI.readNum(strTongTienBan);
            String docThanhChu = "";
            for (int i = 0; i < kq.size(); i++) {
                docThanhChu += kq.get(i)+ " ";
            }
            txtDocThanhChu.setText("("+ docThanhChu +")");
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("In hóa đơn");
        job.setPrintable(new Printable() {
            
            public int print(Graphics grphcs, PageFormat pf, int pageNum){ //To change body of generated methods, choose Tools | Templates.
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
            
                Graphics2D g2 = (Graphics2D) grphcs;   
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.5, 0.5);
                pnInHoaDon.print(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean ok = job.printDialog();
        if (ok) {
            try {
                job.print();
            } catch (PrinterException e) {
            }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        if (soChungTuXuat == null) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn hóa đơn");
            return;
        }
        
        InHoaDon.setVisible(true);
        InHoaDon.setLocationRelativeTo(null);
        hienThiInHoaDon();
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonXuatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonXuatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonXuatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonXuatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonXuatUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog InHoaDon;
    private javax.swing.JDialog SuaHoaDonXuat;
    private javax.swing.JDialog ThemHoaDonXuat;
    private javax.swing.JButton btbLuuHoaDonXuat;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnSuaHoaDonXuat;
    private javax.swing.JButton btnThemHoaDonXuat;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoaHoaDonXuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNgayGioXuat;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSoChungTuXuat;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JPanel pnInHoaDon;
    private javax.swing.JTable tbHoaDonXuatThuoc;
    private javax.swing.JTable tbInHoaDon;
    private javax.swing.JLabel txtDocThanhChu;
    private com.toedter.calendar.JDateChooser txtNgayGioXuat;
    private com.toedter.calendar.JDateChooser txtNgayGioXuatSua;
    private javax.swing.JTextField txtSoChungTuSua;
    private javax.swing.JTextField txtTongTienXuat;
    private javax.swing.JTextField txtTongTienXuatSua;
    // End of variables declaration//GEN-END:variables


}
